

const LOGGED_IN = 'LOGGED_IN';
const AUTHENTICATION_REQUIRED = 'AUTHENTICATION_REQUIRED';
const PLUGIN_LIST_FETCHED = 'PLUGIN_LIST_FETCHED';
const PLUGIN_FETCHED = 'PLUGIN_FETCHED';
const PLUGIN_CREATED = 'PLUGIN_CREATED';
const PLUGIN_FIELD_CHANGED = 'PLUGIN_FIELD_CHANGED';
const INSTALL_STEP_FIELD_CHANGED = 'INSTALL_STEP_FIELD_CHANGED';
const INSTALL_STEP_ADD = 'INSTALL_STEP_ADD';
const PLUGIN_SAVED = 'PLUGIN_SAVED';
const FETCH_ERROR = 'FETCH_ERROR';
const FILE_LIST_FETCHED = 'FILE_LIST_FETCHED';

export {
  LOGGED_IN,
  PLUGIN_LIST_FETCHED,
  PLUGIN_FETCHED,
  PLUGIN_CREATED,
  PLUGIN_FIELD_CHANGED,
  INSTALL_STEP_FIELD_CHANGED,
  INSTALL_STEP_ADD,
  PLUGIN_SAVED,
  FILE_LIST_FETCHED
};
